namespace Herbfunk.GarrisonBase.Garrison.Enums
{
    public enum CombatAbilities
    {
        DangerZones = 6,
        DeadlyMinions=9,
        GroupDamage=3,
        MagicDebuff=4,
        MassiveStrike=2,
        MinionSwarms=7,
        PowerfulSpell=8,
        TimedBattle=10,
        WildAggression = 1,

        Desert=22,
        Forest=26,
        HearthstoneTable,
        Jungle=25,
        Mountains=21,
        Plains = 29,
        Snow=23,
        Swamp = 28,
        Town=27,
        Underground=24,

        Mining,
        Herbalism,
        Alchemy,
        Blacksmithing,
        Enchanting,
        Inscription,
        Engineering,
        Jewelcrafting,
        Leatherworking,
        Tailoring,
        Skinning,


        GnomeLover,
        Humanist,
        Dwarvenborn,
        ChildoftheMoon,
        AllyofArgus,
        CanineCompanion,
        BrewAficionado,
        ChildofDraenor,
        DeathFascination,
        Totemist,
        VoodooZealot,
        Elvenkind,
        Economist,
        HighStamina,
        BurstofPower,
        LoneWolf,
        FastLearner,
        Scavenger,
        ExtraTraining,
        CombatExperience,
        EpicMount,
        Bodyguard,
        HearthstonePro,

        Aberration,
        Arakkoa,
        Beast,
        Breaker,
        Demon,
        Fury,
        Ogre,
        Orc = 11,
        Primal,
        Undead,
    }
}