//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Herbfunk.GarrisonBase.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Herbfunk.GarrisonBase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local wipe = wipe 
        ///local next = next 
        ///local pairs = pairs 
        ///local GARRISON_CURRENCY = GARRISON_CURRENCY 
        ///local GarrisonMissionFrame = GarrisonMissionFrame 
        ///local After = C_Timer.After 
        ///local GARRISON_FOLLOWER_IN_PARTY = GARRISON_FOLLOWER_IN_PARTY 
        ///local GetFramesRegisteredForEvent = GetFramesRegisteredForEvent 
        ///local CANCEL = CANCEL 
        ///local HybridScrollFrame_GetOffset = HybridScrollFrame_GetOffset 
        ///local GetCurrencyInfo = GetCurrencyInfo 
        ///local MissionPageFollowers = GarrisonMissionFrame.MissionTab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LuaString {
            get {
                return ResourceManager.GetString("LuaString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local wipe = wipe 
        ///local next = next 
        ///local pairs = pairs 
        ///local GARRISON_CURRENCY = GARRISON_CURRENCY 
        ///local GarrisonMissionFrame = GarrisonMissionFrame 
        ///local After = C_Timer.After 
        ///local GARRISON_FOLLOWER_IN_PARTY = GARRISON_FOLLOWER_IN_PARTY 
        ///local GetFramesRegisteredForEvent = GetFramesRegisteredForEvent 
        ///local CANCEL = CANCEL 
        ///local HybridScrollFrame_GetOffset = HybridScrollFrame_GetOffset 
        ///local GetCurrencyInfo = GetCurrencyInfo 
        ///local MissionPageFollowers = GarrisonMissionFrame.MissionTab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LuaStringAddon {
            get {
                return ResourceManager.GetString("LuaStringAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local button = gmm_buttons[button_name] 
        ///   if button then button:Click() end 
        ///end.
        /// </summary>
        internal static string LuaStringAddonClickButton {
            get {
                return ResourceManager.GetString("LuaStringAddonClickButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local filtered_followers, filtered_followers_count = GetFilteredFollowers() 
        ///	C_Garrison.GetAvailableMissions(available_missions) 
        ///   local mission 
        ///   for idx = 1, #available_missions do 
        ///      if available_missions[idx].missionID == mission_id then 
        ///         mission = available_missions[idx] 
        ///         break 
        ///      end 
        ///   end 
        ///
        ///
        ///
        ///   FindBestFollowersForMission(mission, filtered_followers, &quot;mission_list&quot;) 
        ///   return top[1] 
        ///end.
        /// </summary>
        internal static string LuaStringAddonSuccess {
            get {
                return ResourceManager.GetString("LuaStringAddonSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return 1 
        ///end.
        /// </summary>
        internal static string LuaStringAddonTest {
            get {
                return ResourceManager.GetString("LuaStringAddonTest", resourceCulture);
            }
        }
    }
}
